name: Deploy needle folder to gh-pages

on:
  push:
    branches:
      - main  # Wenn du auf main pushst

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # Keine GitHub Token Credentials weitergeben
        fetch-depth: 0             # Voller Klon, damit wir alle Branches sehen

    - name: Setup Node.js (falls Build nötig)
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Beispiel, falls du einen Build machen musst

    # Optional: Build-Schritt hier, wenn nötig
    # - run: npm install
    # - run: npm run build

    - name: Deploy needle to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Needle/Scene1
        publish_branch: gh-pages
